# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='crystal_habit',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mineral',
            name='refractive_index',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mineral',
            name='specific_gravity',
            field=models.CharField(default='', max_length=255),
        ),
    ]
